// Module included in the following assemblies:
//
// * networking/configureing-high-performance-multicast-with-SRIOV.adoc

= About high performance multicast

Openshift SDN supports multicast traffic between pods over the default 
pod-to-pod network, however it is best suited for lower bandwidth applications
or service discovery. For high bandwidth streaming media, such as IPTV and
multipoint videoconferencing, SR-IOV can be utilized to provide bandwidth
rates which nearly match the native performance of hardware devices.

When using SRIOV additional interface for multicast:

* Multicast packages sent or received by a Pod through the additional SR-IOV
interface.
* The physical network which connects the SR-IOV interfaces decides the
multicast routing and topology, which is not controlled by Openshift.

= Using SR-IOV interface for multicast

Take following procedure as an example.

.Prerequisites

* Install the OpenShift Command-line Interface (CLI), commonly known as `oc`.
* You must log in to the cluster with a user that has the `cluster-admin` role.
* You must have installed the SR-IOV Operator.

.Procedure
. Create a SriovNetworkNodePolicy CR

+
[source,yaml]
----
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-example
  namespace: openshift-sriov-network-operator
spec:
  resourceName: example
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 4
  nicSelector:
    vendor: "8086"
    pfName: ['ens803f0']
    rootDevices: ['0000:86:00.0']
----

. Create a SriovNetwork CR
+
[source,yaml]
----
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: net-example
  namespace: openshift-sriov-network-operator
spec:
  networkNamespace: default
  ipam: |
    {
      "type": "host-local", <1>
      "subnet": "10.56.217.0/24",
      "rangeStart": "10.56.217.171",
      "rangeEnd": "10.56.217.181",
      "routes": [
        {"dst": "224.0.0.0/5"},
        {"dst": "232.0.0.0/5"}
      ],
      "gateway": "10.56.217.1"
    } 
  resourceName: example
----
<1> Make sure to provision the following static routes through your DHCP server
224.0.0.0/5, 232.0.0.0/5, if you choose to use DHCP as IPAM. This is to override
the static multicast route set by Openshift-SDN.

. User can create a Pod with multicast application
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: net-example
spec:
  containers:
  - name: example 
    image: rhel7:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"] <1>
    command: [ "sleep", "infinity"]
----
<1> The NET_ADMIN capability is only required if your application needs to 
assign the multicast IP address to the SRIOV interface. Otherwise, it can be
omitted.
